### ISSUE TITLE
React Dom issues with charCodes and shouldAddOnBlur props

### ISSUE THREAD

**Issue by MrCEO63** [blackjackkent/react-multivalue-text-input#24]
Warning: React does not recognize the `charCodes` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `charcodes` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by MultipleValueTextInput)
    in label (created by MultipleValueTextInput)
    in div (created by MultipleValueTextInput)
    in MultipleValueTextInput (at App.js:8)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)
Warning: React does not recognize the `shouldAddOnBlur` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `shouldaddonblur` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in input (created by MultipleValueTextInput)
    in label (created by MultipleValueTextInput)
    in div (created by MultipleValueTextInput)
    in MultipleValueTextInput (at App.js:8)
    in App (at src/index.js:9)
    in StrictMode (at src/index.js:8)

**Comment by upadhyan** [comment]
I'm having the same issue. it doesnt impede functionality, but it is annoying

**Comment by MrCEO63** [comment]
Did a pull request and sent him an email but still hasn't merged it yet. He promised to do so, but I guess he is busy.

**Comment by blackjackkent** [comment]
Hello! I'm so sorry, I've had an extremely hectic couple months and haven't had a chance to take a look into this. I'll have a look today.
