### ISSUE TITLE
Project scss file not supporting. Scss file parse failed

### ISSUE THREAD

**Issue by dhheeraj** [blackjackkent/react-multivalue-text-input#26]
installed the papckage with npm, failing in build.
![issue](https://user-images.githubusercontent.com/25099421/107323993-3bdb4d80-6acd-11eb-9b8d-a23c9b894a84.JPG)

package-json-
"dependencies": {
    "@microsoft/sp-core-library": "1.11.0",
    "@microsoft/sp-lodash-subset": "1.11.0",
    "@microsoft/sp-office-ui-fabric-core": "1.11.0",
    "@microsoft/sp-property-pane": "1.11.0",
    "@microsoft/sp-webpart-base": "1.11.0",
    "@pnp/polyfill-ie11": "^2.0.2",
    "@pnp/sp": "^2.0.10",
    "@pnp/spfx-controls-react": "^2.4.0",
    "lodash": "^4.17.20",
    "office-ui-fabric-react": "6.214.0",
    "react": "16.8.5",
    "react-dom": "16.8.5",
    "react-quill": "^1.3.5",
    "react-router-dom": "^5.2.0"
  },
  "devDependencies": {
    "@types/react": "16.8.8",
    "@types/react-dom": "16.8.3",
    "@microsoft/sp-build-web": "1.11.0",
    "@microsoft/sp-tslint-rules": "1.11.0",
    "@microsoft/sp-module-interfaces": "1.11.0",
    "@microsoft/sp-webpart-workbench": "1.11.0",
    "@microsoft/rush-stack-compiler-3.3": "0.3.5",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "@types/webpack-env": "1.13.1",
    "@types/es6-promise": "0.0.33"
  }

node -v = 10.16

**Comment by michaelcuneo** [comment]
Looks like you need a webpack loader for scss... 

sass-loader node-sass.

**Comment by blackjackkent** [comment]
Hey! I'm so sorry for the massive delay in responding on this. Version 0.7.0, just published, removes the SASS/SCSS dependency so you no longer need a loader for it as part of your process. :)

Thanks for letting me know about this!
