### ISSUE TITLE
Jest unit tests are unable to detect the new typescript version of module during import. 

### ISSUE THREAD

**Issue by maheedhar1305** [blackjackkent/react-multivalue-text-input#38]
Steps to reproduce :
1. Create a hello world react app : https://reactjs.org/docs/create-a-new-react-app.html#create-react-app
2. Install `npm install react-multivalue-text-input@1.0.0` which was the last version of the module to be written in javascript. 
3. Add the component to the App.js in a straightforward manner 

```
function App() {
  return (
    <div className="App">
      <header>hello world</header>
      <MultipleValueTextInput />
    </div>
  );
}
```

4. write a simple App.test.js and run the following test using `npm test`

```
import { render, screen } from '@testing-library/react';
import App from './App';

test('renders learn react link', () => {
  render(<App />);
  const element = screen.getByText(/hello world/i);
  expect(element).toBeInTheDocument();
});
```
5. This is successful
6. Now update the 'react-multivalue-text-input' to its latest version 2.1.0
7. Without any code changes, run `npm test` again and the following error occurs

```
 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module 'react-multivalue-text-input' from 'src/App.js'

    Require stack:
      src/App.js
      src/App.test.js

      2 | import './App.css';
      3 | import React from 'react';
    > 4 | import MultipleValueTextInput from "react-multivalue-text-input";
        | ^
      5 |
      6 | function App() {
      7 |   return (

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/App.js:4:1)

```

Some folks who have had similar issues with other TS libs have fixed it by forcing jest to transpile the .ts files using a different preset (ts-jest) which solved the issue but I have tried several of the popular workarounds and none seem to work. This is my `jest.config.js` file. 

```
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  "verbose": true,
  "transform": {
    "^.+\\.jsx$": "babel-jest",
    "^.+\\.js$": "babel-jest",
    "^.+\\.ts$": "ts-jest"
  },
  "moduleFileExtensions": [
    "js",
    "jsx",
    "ts"
  ],
  "moduleDirectories": [
    "node_modules"
  ],
  "transformIgnorePatterns": [
    "node_modules/(?!react-multivalue-text-input/)"
  ]
};
```

I just wanted to drop a note here in case I was missing something super obvious. Any help is greatly appreciated. Thanks

**Comment by blackjackkent** [comment]
Thanks for letting me know about this. I'll do some digging and get back to you. :)

**Comment by blackjackkent** [comment]
I did some looking into this and I'm not entirely sure what's up - I think this may be a problem with how I configured the package, not with how your project is set up, but I'm not sure what that problem is.

I'm out of town tomorrow through midday Monday, but I have a StackOverflow post up seeking some more help and will dive further into this as soon as I'm back. :)

Thanks much for letting me know about this!

**Comment by maheedhar1305** [comment]
Thanks for confirming the issue. I will keep an eye out for updates.

**Comment by blackjackkent** [comment]
It looks like this was indeed a problem with my configuration of the package in the new version: https://stackoverflow.com/a/75029020/811189

This has definitely been a learning experience for me. 

I will push a fix as soon as I am back from traveling, unless you want to test this and make a PR if the fix works.

Steps:
- Change `module` key to `main` in package.json
- Run `npm run build`
- Copy the generated `dist` folder and use it to completely replace `node_modules/react-multivalue-text-input/dist` in your test project.
- Rerun `npm run test`

If this by itself is enough to fix the issue, you can make a PR with the package.json change (including a minor version bump to 2.3.0).

If it doesn't work, or if you don't feel like fiddling with it, I'll get things sorted when I get home. :)

Thanks again!

**Comment by maheedhar1305** [comment]
Hey, thanks for circling back to me on this. I will try to check on this the upcoming weekend and let you know if the issue goes away for me

**Comment by blackjackkent** [comment]
v2.3.0 has been deployed with a fix to the `main` keyword in package.json; as near as I can tell from my own tests, this has resolved the issue, but please feel free to reopen this if it's still misbehaving!
