### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by mledwards** [blackjackkent/react-multivalue-text-input#40]
I'm getting this error coming up from just importing the package at the top. Any ideas?
`import MultipleValueTextInput from "react-multivalue-text-input";`

Wondering if it's SSR related, as I'm using next.js?

![image](https://user-images.githubusercontent.com/2692615/228508479-b6a72b1c-6b75-4f9b-ade7-dffc2c0054dd.png)

**Comment by blackjackkent** [comment]
Hey! Thanks so much for highlighting this. It looks like there is indeed some further config I could do on my end to make this work for nextjs SSR as well. (Apologies - this is my first NPM module and there have been some hiccups. 😭 )

I'll try to work on this this evening and have a fix up soon.

**Comment by mledwards** [comment]
No worries! Whenever I hit an issue like this in next.js, it's usually that I'm referring to a client side only thing like `window` outside of a client side only react function like useEffect. Let me know if I can help!

**Comment by blackjackkent** [comment]
@mledwards I've released v2.4.0 which I believe should resolve this issue by creating proper CJS and ESM versions of the package for import in browser and Node (i.e. SSR, in this case) contexts. Testing on my end seems to be behaving itself but can you please verify this new release when you have a chance and let me know if everything looks okay? :)

Thanks again so much for highlighting this issue!

**Comment by mledwards** [comment]
This works a treat, thank you! I've switched out another package for this one I was using that didn't quite do what I wanted, like this one does :)

**Comment by blackjackkent** [comment]
@mledwards Fantastic, I'm glad to hear it! Thanks again so much for prompting me to look into this, and please don't hesitate to reach out again if you run into further issues. :)
