### ISSUE TITLE
Cannot update `values` after initial render (dynamically)

### ISSUE THREAD

**Issue by mledwards** [blackjackkent/react-multivalue-text-input#42]
Hello, it's me again, Next.js / SSR guy :)

I'd like to initialise the `values` property dynamically, but it doesn't see to work.

If I set `values={["test"]}` that works, but if I set them in a use effect (after data is fetched), it doesn't.

```
useEffect(() => {
    setEmails(["test"])
  }, [])
```

Any ideas?

**Comment by blackjackkent** [comment]
Hey! Thanks so much for reaching out about this; it's definitely a good use case for me to address. :)

Thinking out loud here - as a consumer of the library, what would you expect the behavior of the component to be when `values` is updated dynamically?

a) Calculate added or removed items and fire `onItemAdded` and `onItemDeleted` individually for each?
b) Add an `onValuesUpdated` handler that fires in this scenario and leave `onItemAdded` and `onItemDeleted` for user input?
c) Major version update - remove `onItemAdded` and `onItemDeleted` interface and replace them with `onValuesUpdated` that fires in all scenarios where `values` is changing?

**Comment by mledwards** [comment]
Hello! The main behaviour I'd expect would be that it populates the input field with the values from the new array. So probably the same as what happens when you add the `values` prop.

It would be risky having this fire the onItem events, as that could get caught in a loop if the `values` property is populated by a state already.

For context, I have a dropdown menu that pre-populates some form fields based on what option is chosen, and one of those fields it pre-populates is an email fields, which is using this package :) All the other fields update as they're based on state change, apart from this one.

**Comment by blackjackkent** [comment]
OK, let me work on adding this behavior and get back to you. :) Thanks for the context!

**Comment by blackjackkent** [comment]
Hey! Really sorry for the delay in followup on this, but I just deployed v2.5.0 which should add this functionality. Please let me know if there's any issues with it that need further tweaking for your use case. :) Thanks again for highlighting this!
